services:
  jenkins:
    image: ${JENKINS_VERSION_IMAGE}
    ports:
      - "8080:8080"
    volumes:
      - "${WIP_ENV}/Jenkins/jenkins_home:/var/jenkins_home"
  ssh-agent:
    image: ${JENKINS_AGENT_VERSION_IMAGE}
volumes:
  jenkins_home: